version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      svelte:
        patterns:
          - 'svelte'
          - 'svelte-*'
          - '@sveltejs/*'
          - 'prettier-plugin-svelte'
          - 'eslint-plugin-svelte'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      types:
        patterns:
          - '@types/*'
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
